### ISSUE TITLE
Problem with symbol/string for options in git describe

### ISSUE THREAD

**Issue by CoRfr** [ruby-git/ruby-git#251]
I have to specify both string and symbol, otherwise it doesn't work:

```
opts[:match] = pattern
opts['match'] = pattern
git.describe(commit, opts)
```

Cause:
Code test if a symbol is present but uses a string to refer to that option:

```
      arr_opts << "--abbrev=#{opts['abbrev']}" if opts[:abbrev]
      arr_opts << "--candidates=#{opts['candidates']}" if opts[:candidates]
      arr_opts << "--match=#{opts['match']}" if opts[:match]
```

**Comment by adityashedge** [comment]
I would like to suggest that we add 'activesupport' [hash](http://www.rubydoc.info/gems/activesupport/4.2.4/Hash) 'with_indifferent_access' for options since changing string to symbol might break someone else's code.

I have already added 'activesupport' for git describe's 'config' hash and if you want I can create a pull request. If needed we can add hash 'with_indifferent_access' in other places as well.

**Comment by no-trick-pony** [comment]
@adityashedge What's the status of this?
And how and whose code would this potentially break? Currently everyone unaware of this issue will have wrong output without any indication on what's causing the problem. The obvious workaround for this is to add the options twice (once with a symbol key, once with a string key). I see this only being broken by using something like {match: true, 'match' => 'ab*'}, where the symbol is only used as a marker for the presence of the key. But If so, this workaround would also break by using with_indifferent_access.
