### ISSUE TITLE
No way to remove a stash

### ISSUE THREAD

**Issue by ph-One** [ruby-git/ruby-git#294]
All of the stash methods either create or apply a `stash`. There needs to be additional functionality for `stash`, such as `stash pop` and `stash drop`. Pull Request https://github.com/schacon/ruby-git/pull/293 .

**Comment by greeneca** [comment]
I for some reason didn't check to see if someone had done this before I did my pull request. I see that you closed your though. It is now Pull Request #297

**Comment by mohkale** [comment]
this issue shouldn't be closed, is there a reason the pull request was never accepted?

**Comment by wwboynton** [comment]
Still an issue.

This stale bot is clearly more trouble than it's worth. It's buried tons of other issues too. I think it can be configured so that it only closes issues where a maintainer was the most recent commenter, otherwise leaving them open to be addressed or put to bed manually, which is ideal.

**Comment by revolter** [comment]
Is there any workaround?
