### ISSUE TITLE
read git data faild "empty string is not a valid pathspec"

### ISSUE THREAD

**Issue by yishuiliunian** [ruby-git/ruby-git#345]
读取Git数据失败git '--git-dir=/Users/dongzhao/Works/QCloud/Src/iOS/Git/QCloudiOSCodes/.git' '--work-tree=/Users/dongzhao/Works/QCloud/Src/iOS/Git/QCloudiOSCodes' ls-files '--stage' ''  2>&1:fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

**Comment by baranga** [comment]
Same here. Looks like git returns a error for empty path spec since version 2.16. The behavior to treat empty path spec as `.` was already deprecated for some versions but now its gone.

**Comment by steventebrinke** [comment]
It looks like defaulting the location parameter of ls_files (lib.rb line 398) to '.' solves this bug for me, but I do not know whether that is a proper and/or complete fix.

**Comment by rafamanzo** [comment]
This really was deprecated since git 2.1.6: https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.16.0.txt

```
An empty string as a pathspec element that means "everything"
i.e. 'git add ""', is now illegal.  We started this by first
deprecating and warning a pathspec that has such an element in
2.11 (Nov 2016).
```

Judging by this changelog entry, the ix here really is using `.`.

I've mapped possible code where this could break the code on [lib.rb](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb):
* line [104](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L104). There is no fix necessary because there is a check for nil values
* line [398](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L398). This is where our bug is needs a fix
* line [409](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L409).  There is no fix necessary because there is a check for nil values
* line [488](https://github.com/ruby-git/ruby-git/blob/master/lib/git/lib.rb#L488). There is no check for nil values. But performing the the following local test raises no errors `Git.open('.').show`. Thus no action is required for this case also.

Thus I'll open a PR fixing the case for line 398.

**Comment by sbussetti** [comment]
Any eta on a new version released with this fix?
