### ISSUE TITLE
Git clone : Avoid host authenticity check

### ISSUE THREAD

**Issue by zedtux** [ruby-git/ruby-git#386]
### Subject of the issue
When cloning a repo, my app is asked about the host authenticity and if it wants to continue:

```
The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)?
```

This blocks my app and I want to answer yes ... but how ?

### Your environment
Doesn't matter.

### Steps to reproduce
```ruby
Git.clone('what ever repo URL you never cloned yet')
```

### Expected behaviour
Passing another option to force accept continuing or something like that should allow the clone to be done without blocking the execution.

### Actual behaviour
It's blocking the code execution.

**Comment by zedtux** [comment]
One option could be to have an option which will then pass an additional flag to the `git` command like it has been done in [this repo](https://github.com/cpliakas/git-wrapper/issues/126#issuecomment-333547680).

**Comment by tarcinil** [comment]
@zedtux ruby-git does not have anyway to disable this at present, as your second post points out, you just need to munge the environment variables to add the following.  If you add this to your scripts, when our library runs, it should get the environment variable in it's child process.

```
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" 
```

We will discuss adding this into our project to ensure that we maintain the experience due to Ruby's one-way inheritance of environment variables.  I think that it is probably a good feature that we add so that we can support non-interactive running but I would admit that there could be security concerns as it pertains to possible man-in-the-middle attacks that the system was created to prevent.

**Comment by zedtux** [comment]
I fully agree with you.

I used the `git_ssh` option to provide a Bash script which is passing the additional flag.

**Comment by zedtux** [comment]
Oh no ... this shitty bot ... again !? 🤦‍♂️.

Please uninstall it, closing issues because of maintainers lack of activity doesn't help AT-ALL.

**Comment by zedtux** [comment]
Yeah congrats ! Nice job bot ! So helpful.

**Comment by zedtux** [comment]
@tarcinil do you have any news on this ticket that you _nice_ bot closed?
