### ISSUE TITLE
`#status` fails on a new repo

### ISSUE THREAD

**Issue by costa** [ruby-git/ruby-git#459]
### Subject of the issue
`Git::GitExecuteError (git '--git-dir=/proj/my-proj/.git' '--work-tree=/proj/my-proj' diff-index 'HEAD'  2>&1:fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.)`
when there is no `HEAD`.

(`$ git status` works fine)

### Your environment
* version of git (2.20.1) and ruby-git (1.6.0)
* version of ruby (2.6.5)

### Steps to reproduce
`$ cd "$(mktemp -d)"; git init .; echo 'Git.open(".").status' | ruby -rgit`

### Expected behaviour
a return value, perhaps?
with untracked/cached files preferably

### Actual behaviour
exception above

**Comment by costa** [comment]
?

**Comment by jelaniwoods** [comment]
@costa This happens to me as well. It looks like the culprit is that `g.status` doesn't actually call the `git status`. It calls `git diff-files` and then [`git diff-index HEAD`](https://github.com/ruby-git/ruby-git/blob/4bef5abbba073c77b4d0ccc1ffcd0ed7d48be5d4/lib/git/status.rb#L194), which will fail since there are no commits.

**Comment by jcouball** [comment]
@costa, agree the bot is a pain.

Which last commit are you talking about?

**Comment by costa** [comment]
Hey @jcouball, sorry for the delay, been a little crazy.

It was an offtopic remark, https://github.com/ruby-git/ruby-git/commit/4bef5abbba073c77b4d0ccc1ffcd0ed7d48be5d4 looks like you haven't set the `author` correctly.
But this is not the issue here, of course.

**Comment by costa** [comment]
@jcouball a friendly reminder that this issue hasn't been resolved yet...
