### ISSUE TITLE
Git.clone requires 2 arguments instead of 1

### ISSUE THREAD

**Issue by sethfri** [ruby-git/ruby-git#565]
### Subject of the issue

In the example usage of `Git.clone`, the [documentation](https://rubydoc.info/gems/git/Git.clone) says that it can be called with only the URL of the repo, like so:

```ruby
git = Git.clone('https://github.com/ruby-git/ruby-git.git')
```

However, the method itself requires both the URL and the name of the directory. You can't just use the default

### Your environment
* Git 2.34.0
* ruby-git 1.8.1
* Ruby 2.7.4

### Steps to reproduce

```ruby
git = Git.clone('https://github.com/ruby-git/ruby-git.git')
```

### Expected behaviour
The clone will work and use `ruby-git` as the default name of the clone directory

### Actual behaviour
The method fails with `wrong number of arguments (given 1, expected 2..3)`

**Comment by masterkain** [comment]
also if you do `g = Git.clone(GIT_URL, branch: 'master')` if will clone into a folder named `{/branch=>"master"}` resulting in

```
/Users/kain/.rvm/gems/ruby-3.0.0/gems/git-1.10.2/lib/git/base.rb:613:in `expand_path': no implicit conversion of Hash into String (TypeError)
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/git-1.10.2/lib/git/base.rb:613:in `normalize_working_directory'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/git-1.10.2/lib/git/base.rb:592:in `normalize_paths'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/git-1.10.2/lib/git/base.rb:22:in `clone'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/git-1.10.2/lib/git.rb:161:in `clone'
	from main.rb:69:in `<main>'
```

**Comment by jcouball** [comment]
Take a look at #578 which makes the `directory` parameter to `Git.clone` optional which means that you can:

```ruby
g = Git.clone('https://github.com/ruby-git/ruby-git')
g.dir.to_s #=> "/Users/couballj/Projects/ruby-git/ruby-git"
```

Since the definition of Git.clone is:

```ruby
def self.clone(repository_url, directory = nil, options = {})
```

In order to pass a an option, you will need to pass `nil` for directory.  So this won't have the desired effect:

```ruby
g = Git.clone(GIT_URL, branch: 'master')
```

Instead, you will need to do this:

```ruby
g = Git.clone(GIT_URL, nil, branch: 'master')
```

I think we will need to transition to using keyword parameters (or move the `directory` parameter to an option) in order to make `Git.clone(url, branch: 'master')` work like you want.
